name: deploy-bio-page

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            joaobatistalimajunior44/portifolio-jbl:v1
            joaobatistalimajunior44/portifolio-jbl:latest

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy Kubernetes manifests
        run: |
          ssh -o StrictHostKeyChecking=no ${{vars.SSH_USERNAME}}"kubectl apply -f ${{vars.REMOTER_DIR}}"

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v2
        with:
          args: "-rlgoDzvc --delete"
          source: "deploy-local/deployments-ingress-controller/"
          remote_host: ${{vars.REMOTE_HOST}}
          remote_user: ${{vars.SSH_USERNAME}}
          remote_port: ${{vars.REMOTE_PORT}}
          target: ${{vars.REMOTER_DIR}}
