name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
         joaobatistalimajunior44/my-portifolis-cicd:v1
         joaobatistalimajunior44/my-portifolis-cicd:latest

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Set Kubernetes context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f deploy-local/deployments-ingress-controller/

      - name: Find Nginx Pod
        run: |
          nginx_pod_name=$(kubectl get pods -l app=nginx -n <seu-namespace> -o jsonpath='{.items[0].metadata.name}')

      - name: Clear Nginx Cache
        run: |
          kubectl exec -n <seu-namespace> $nginx_pod_name -- rm -rf /var/cache/nginx/*

      - name: Reload Nginx
        run: |
          kubectl exec -n <seu-namespace> $nginx_pod_name -- nginx -s reload
