name: TEsting Pipilane

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print build message
        run: echo "This is a fictitious build process."

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.REMOTE_HOST }} "echo Connected to server successfully"

      - name: Deploy Kubernetes manifests
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.REMOTE_HOST }} "kubectl apply -f ${{ secrets.REMOTE_DIR }}"

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v2
        with:
          args: "-rlgoDzvc --delete"
          source: "deploy-local/deployments-ingress-controller/"
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          target: ${{ secrets.REMOTE_DIR }}
